# Generated by Django 4.2.2 on 2023-07-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('aluno', '0002_rename_matricula_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
