# Generated by Django 4.2.2 on 2023-07-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidade', '0001_initial'),
        ('aluno', '0003_alter_aluno_curso_delete_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidade.cidade'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
